/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlks.view.employee;

import qlks.view.employee.EmployeeFrame;
import java.sql.DriverManager;
import java.sql.SQLException;
import qlks.dao.JDBCconnection;
import java.sql.*;
import javax.swing.JOptionPane;
import qlks.modal.Employee;
import qlks.service.EmployeeService;

/**
 *
 * @author Admin
 */
public class EditEmployeeFrame extends javax.swing.JFrame {

    private Employee employee;
    EmployeeService employeeService;
    /**
     * Creates new form EditEmployeeFrame
     */
    private java.sql.Connection connection;

    public java.sql.Connection getConnection() {
        return connection;
    }

    public void setConnection(java.sql.Connection conn) {
        this.connection = conn;
    }

    public java.sql.Connection getConnect() throws ClassNotFoundException, SQLException {
        Class.forName(JDBCconnection.driverName);
        connection = DriverManager.getConnection(JDBCconnection.dbURL, JDBCconnection.dbUser, JDBCconnection.dbPass);
        System.out.println("CONNECTTED!");
        return connection;
    }

    public EditEmployeeFrame(int EmployeeId) throws ClassNotFoundException, SQLException {
        initComponents();
        employee = new Employee();
        employeeService = new EmployeeService();
        employee = employeeService.getEmployee(EmployeeId);

        inputID.setText(String.valueOf(employee.getId()));
        inputName.setText(employee.getName());
        inputAge.setText(employee.getAge());
        inputGender.setSelectedItem(employee.getGender());
        inputJob.setSelectedItem(employee.getJob());
        inputLuong.setText(employee.getLuong());
        inputPhone.setText(employee.getPhone());
        inputAddr.setText(employee.getDiaChi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputAge = new javax.swing.JTextField();
        inputGender = new javax.swing.JComboBox<>();
        inputJob = new javax.swing.JComboBox<>();
        inputLuong = new javax.swing.JTextField();
        inputPhone = new javax.swing.JTextField();
        inputAddr = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Khách Sạn - Sửa Thông Tin Nhân Viên");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sửa Thông tin Nhân Viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 250, 36));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 96, 65, -1));

        inputID.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputID.setEnabled(false);
        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });
        getContentPane().add(inputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 93, 91, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 136, 37, -1));

        inputName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        getContentPane().add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 133, 160, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tuổi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 176, 37, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới tính");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 216, 65, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chức vụ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 256, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lương");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 296, 53, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số điện thoại");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 336, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Địa chỉ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 376, 60, -1));

        inputAge.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(inputAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 173, 160, -1));

        inputGender.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        getContentPane().add(inputGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 213, 106, -1));

        inputJob.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Lễ tân", "Bồi bàn", "Bếp trưởng", "Bếp phó", "Phụ bếp", "Phục vụ phòng", "Dọn phòng", "Bảo vệ" }));
        getContentPane().add(inputJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 253, 160, -1));

        inputLuong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(inputLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 293, 160, -1));

        inputPhone.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(inputPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 333, 164, -1));

        inputAddr.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(inputAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 373, 164, -1));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnSubmit.setText("OK");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 434, 98, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/img/4909.jpg_wh860.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String gender = (String) inputGender.getSelectedItem();
        String job = (String) inputJob.getSelectedItem();
        try {
            connection = getConnect();

            String sql = "update employee set TenNV = N'"+inputName.getText()+"', Age = '"+inputAge.getText()+"', gender = N'"+ gender+"' , job = N'"+job+"', Luong = '"+inputLuong.getText()+"', phone = '"+inputPhone.getText()+"', Diachi = N'"+inputAddr.getText()+"' where ID = "+inputID.getText()+"";
            
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            int rs = preparedStatement.executeUpdate();

            JOptionPane.showMessageDialog(null, "Sửa thành công thông tin");
            
            new EmployeeFrame().setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField inputAddr;
    private javax.swing.JTextField inputAge;
    private javax.swing.JComboBox<String> inputGender;
    private javax.swing.JTextField inputID;
    private javax.swing.JComboBox<String> inputJob;
    private javax.swing.JTextField inputLuong;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
