/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlks.view.room;

import qlks.view.room.AllRoomFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import qlks.dao.JDBCconnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class AddRoomFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddRoomFrame
     */
    //    SQL
    private java.sql.Connection connection;

    public java.sql.Connection getConnection() {
        return connection;
    }

    public void setConnection(java.sql.Connection conn) {
        this.connection = conn;
    }

    public java.sql.Connection getConnect() throws ClassNotFoundException, SQLException {
        Class.forName(JDBCconnection.driverName);
        connection = DriverManager.getConnection(JDBCconnection.dbURL, JDBCconnection.dbUser, JDBCconnection.dbPass);
        System.out.println("CONNECTTED!");
        return connection;
    }

    public AddRoomFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputMP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        inputClean = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inputBedType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        inputPrice = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Khách Sạn - Trang Thêm Phòng");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Thêm Phòng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 45));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Mã Phòng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 90, 25));

        inputMP.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMPActionPerformed(evt);
            }
        });
        getContentPane().add(inputMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 167, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Tình trạng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 90, 26));

        inputStatus.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Đang thuê" }));
        inputStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStatusActionPerformed(evt);
            }
        });
        getContentPane().add(inputStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 167, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Vệ sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, 29));

        inputClean.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputClean.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã vệ sinh", "Chưa vệ sinh" }));
        getContentPane().add(inputClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 167, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Loại giường");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        inputBedType.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputBedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi", " " }));
        getContentPane().add(inputBedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 167, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Giá");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 37, -1));

        inputPrice.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPriceActionPerformed(evt);
            }
        });
        getContentPane().add(inputPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 167, -1));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnSubmit.setText("Thêm");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 190, 31));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/img/delete-1-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 35, 31));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/img/hinh-anh-phong-khach-san-pansy.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(800, 852));
        jLabel7.setMinimumSize(new java.awt.Dimension(800, 852));
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 852));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMPActionPerformed

    private void inputStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStatusActionPerformed

    private void inputPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPriceActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String MP = inputMP.getText();
        String price = inputPrice.getText();
        String Status = (String) inputStatus.getSelectedItem();
        String Clean = (String) inputClean.getSelectedItem();
        String Bed = (String) inputBedType.getSelectedItem();

        try {
            if (MP.equals("") || price.equals("")) {
                JOptionPane.showMessageDialog(null, "Không được để trống thông tin");
            } else {
                connection = getConnect();
                String str = "INSERT INTO Loai_Phong values( N'" + MP + "', N'" + Status + "', N'" + Clean + "',N'" + Bed + "', '" + price + "')";
                
                PreparedStatement preparedStatement = connection.prepareStatement(str);
                
                int rs = preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Thêm Phòng thành công");
                new AllRoomFrame().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new AllRoomFrame().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddRoomFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddRoomFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRoomFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> inputBedType;
    private javax.swing.JComboBox<String> inputClean;
    private javax.swing.JTextField inputMP;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JComboBox<String> inputStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
